# Generated by Django 4.1.1 on 2022-09-10 05:57

import django.db.models.deletion
import django.utils.timezone
from model_utils.fields import AutoCreatedField, MonitorField
from django.db import migrations, models
from django_state_machine_demo.orders.models import Order
from django_state_machine_demo.utils.enums import EnumField


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item", models.CharField(max_length=100, verbose_name="Item")),
                (
                    "state",
                    EnumField(
                        default="pending_payment",
                        enum_cls=Order.State,
                        max_length=16,
                        verbose_name="State",
                    ),
                ),
                (
                    "state_changed",
                    MonitorField(
                        default=django.utils.timezone.now,
                        monitor="state",
                        verbose_name="State Changed",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Price"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Timestamp"
                    ),
                ),
                (
                    "old_state",
                    EnumField(
                        enum_cls=Order.State,
                        max_length=16,
                        verbose_name="Old State",
                    ),
                ),
                (
                    "new_state",
                    EnumField(
                        enum_cls=Order.State,
                        max_length=16,
                        verbose_name="New State",
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="Extra")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Log",
                "verbose_name_plural": "Order Logs",
                "db_table": "order_logs",
            },
        ),
    ]
